spring.application.name=cassandra-activity-log-app

spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.keyspace-name=activity_log_app
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=none

server.port=8080