spring.application.name=cassandra-activity-log-app

spring.cassandra.contact-points=127.0.0.1:9042,127.0.0.1:9043,127.0.0.1:9044
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=activity_log_app
spring.cassandra.schema-action=none
spring.cassandra.request.timeout=10s
spring.cassandra.connection.connect-timeout=10s
spring.cassandra.connection.init-query-timeout=10s
spring.cassandra.request.consistency=LOCAL_QUORUM
spring.cassandra.request.serial-consistency=LOCAL_SERIAL

server.port=8080